### ISSUE TITLE
Update polynomial 2 model documentation (2023)

### ISSUE THREAD

**Issue by sedavid01** [USEPA/CompTox-ToxCast-tcplFit2#11]
The current parameterization of the polynomial 2 model diverges from that of BMDS and BMDExpress.  It assumes that the background response is always at zero and also does not allow for fitting of biphasic responses (that is, an observed response which increases in the low dose region then changes directionality and decreases in higher doses, or vice versa).

Needs:

- Include a note that this model parameterization of poly2 does not allow for fitting biphasic responses.
- Include a note that this model parameterization diverges from the polynomial 2 model that is in BMDS and BMDExpress.

**Comment by sedavid01** [comment]
Current blocker, does the optimization in tcplfit2 for the poly2 model allow for the "b" parameter to be negative?
Does constOptim allow for any of the constraints to be negative for any of the parameters within a specified function?

**Comment by gracezhihuizhao** [comment]
> 
The current implementation of poly2 in tcplfit2 will always have a lower limit of 1e^-8*conc_max constrain on the "b" parameter, it's a very small number so basically it's a positive boundary for "b". constOptim should allow for negative constraints for any of the parameters that we want to optimize.

**Comment by sedavid01** [comment]
Thank you for looking into this, @gracezhihuizhao.

**Comment by sedavid01** [comment]
@gracezhihuizhao, can you please follow-up on the poly2 updates to check whether the poly2 modeling function(s) had their documentation updated with https://github.com/USEPA/CompTox-ToxCast-tcplFit2/issues/69.  If yes, please just make a comment here and I can close this ticket out.

**Comment by gracezhihuizhao** [comment]
> @gracezhihuizhao, can you please follow-up on the poly2 updates to check whether the poly2 modeling function(s) had their documentation updated with #69. If yes, please just make a comment here and I can close this ticket out. If no, then please work on updating the relevant modeling functions.

Yes, the documentations are updated in #69.

**Comment by sedavid01** [comment]
Thanks, @gracezhihuizhao for following-up.  Closing out this ticket as this has already been resolved.
