### ISSUE TITLE
concRespPlot2 Issue with Data with both Replicates & Untreated Control Samples (conc = 0)

### ISSUE THREAD

**Issue by sedavid01** [USEPA/CompTox-ToxCast-tcplFit2#113]
Goal: concRespPlot2 should be able to function with datasets containing replicates and/or untreated (conc = 0) samples.

Issue:
* When converting raw concentrations to log10 scale with replicate data the current code assumes there are no duplicated concentrations, which is causing issues with reassigning the pseudo value to the 'untreated' conc for x-axis scaling.

Needs: Update the code below.
Line 38: `sort(conc)[2]` should be `sort(unique(conc))[2]`

Requirement for Approval of PR:
* Test the code prior to fix with replicate data including an untreated control group (conc = 0) -> should produce an error
* Fix the code
* Test the code resolves issues (i.e. no error) and produces a plot with observed replicate responses.

**Comment by derikhaggard** [comment]
Here's a reproducible example of the error (error message from console in bold face):

conc <- list(0, .1, .3, 1, 3, 10, 30, 100, 0, .1, .3, 1, 3, 10, 30, 100)
resp <- list(0.01, .2, .1, .4, .7, .9, .6, 1.2, 0.01, .2, .1, .4, .7, .9, .6, 1.2)
row <- list(conc = conc,
             resp = resp,
             bmed = 0,
             cutoff = 0.25,
             onesd = 0.125,
             name = "some chemical",
             assay = "some assay")
res <- concRespCore(row, conthits = TRUE)
concRespPlot2(res, log_conc = T)

**Error in seq.default(from = min(conc), to = max(conc), length = 100) : 
  'from' must be a finite number
In addition: Warning message:
In concRespPlot2(res, log_conc = T) :
  Data contains untreated controls (conc = 0). A pseudo value replaces -Inf after log-transform.  The pseudo value is set to one log-unit below the lowest experimental `conc`.**

**Comment by derikhaggard** [comment]
Accidentally closed the ticket. See above for a reproducible example.

**Comment by sedavid01** [comment]
@knuppla, please test this in "dev".  Looking at the code this may be an issue which is already resolved in "dev" but not in the recently released version in CRAN.
