### ISSUE TITLE
Add further descriptions about model parameters in documentation

### ISSUE THREAD

**Issue by sedavid01** [USEPA/CompTox-ToxCast-tcplFit2#16]
All of the models available in tcplfit2 have brief information about the parameters, but some of the descriptions are common across model documentation though may have slightly different interpretations given the model of interest.

Needs:
* Understand what the model parameters mean and how they impact the shape of the resulting curve.
* Understand what the model parameters mean in terms of the biological response - that is how do you use these for interpretation (if applicable).
* Add brief descriptions about each of the model parameters with the two bits of information collected in the bullets above.  This will help users to more intuitively understand and accurately interpret the models/results.

**Comment by sedavid01** [comment]
1. Make a list of parameters in available tcplfit2 models.
2. Obtain current descriptions of model parameters (for example, gain and loss parameters with relation to AC50)
3. Draft description of models and how they impact/relate to the model shape.
4. Set-up meeting with SME's - Katie, Kelly, Logan, Richard, and Sarah. (Look out the next 2-3 weeks for best availability for all individuals.)

**Comment by sedavid01** [comment]
From discussion with the SME's and main users of tcplfit2, path forward:
* Simplify (i.e. reduce redundancy) and clarify some of the parameter descriptions on impact of various parameter values on curve shape.
* Create a vignette that contains the parameter descriptions alongside plots to demonstrate changes in curve shape as parameter values change.
* Can extend off of the descriptions provided in https://cran.r-project.org/web/packages/tcpl/vignettes/Data_processing.html#concentration-response-modeling-details.
* In the individual function document descriptions can link out to the vignette for further details on the impact of various parameters on the resulting curve shape.

**Comment by sedavid01** [comment]
From our discussion this morning, ensure that when you are developing this vignette it is a "stand-alone" vignette that users can open and read.  That is, provides a single module of how the various model parameters impact curve shapes.

Focus on just the continuous models for now.  Once the dichotomous models are pulled into the package then we can update this vignette.

**Comment by madison-feshuk** [comment]
#45 The original development branch was already merged so this ticket should have been closed.
