### ISSUE TITLE
Create initial unit test for tcplfit2

### ISSUE THREAD

**Issue by brown-jason** [USEPA/CompTox-ToxCast-tcplFit2#17]
Find an example set of data that is identical to something that would be processed in httr or toxcast and create a test using testthat package so that when we make changes in the future we can ensure the current analyses are not effected 

1.  Research testthat package
2.  Create a test with a known output that tests concrespcore function and ensures repeatable output

**Comment by sedavid01** [comment]
@brown-jason, we may also want to get an example from Josh Harrill or Derik Haggard for HTPP data.

**Comment by sedavid01** [comment]
For now, let us start with a simulation example for testing, then we can add in 'example data' from the various potential data streams.
See code chunk above "General Shape" figure in the tcpl_v3 Data processing vignette as an example for simulation data if needed.  Suggest only using at the very least 5 doses and likely no more than 10 doses for simulated DR data.
