### ISSUE TITLE
Update the tcplfit2 vignette to address tech review comments

### ISSUE THREAD

**Issue by sedavid01** [USEPA/CompTox-ToxCast-tcplFit2#20]
PDF from Logan Everett has comments on updating the vignette for users to better follow examples.
1. Review PDF attached by @brown-jason from the tech review.
2. Make suggested updates per the comments in the vignette - some may have several resolution options (discuss to determine path forward).
3. Recompile the vignette PDF to ensure everything looks (attach to ticket or PR for review).

**Comment by sedavid01** [comment]
Target wrap-up on this is COB 09/01/2023.

**Comment by gracezhihuizhao** [comment]
@sedavid01 Hi Sarah, I made some updates to address the review from Logan. Below attached are the recompiled pdf vignette with the new changes and the pdf with Logan's comment with my comments added. Please let me know if you have trouble accessing. 
[tcplfit2-vignette-LJE-comments-added.pdf](https://github.com/USEPA/CompTox-ToxCast-tcplFit2/files/12467601/tcplfit2-vignette-LJE-comments-added.pdf)
[tcplfit2-vignette-updated.pdf](https://github.com/USEPA/CompTox-ToxCast-tcplFit2/files/12467603/tcplfit2-vignette-updated.pdf)

**Comment by brown-jason** [comment]
looks good to me, I added some info to the docs and updated the .Rd files with devtools::document() submitting a PR for Sarah to look at.

**Comment by sedavid01** [comment]
This looks good overall, @gracezhihuizhao.  There are some small changes based on our conversation earlier.  Going to go ahead and just make the changes if you are okay with that as they are very minor.  We can discuss them and any other changes that may need to be done/addressed.
