### ISSUE TITLE
Add the Rmd for Conducting unit tests & polishing for future developers

### ISSUE THREAD

**Issue by sedavid01** [USEPA/CompTox-ToxCast-tcplFit2#44]
#17, @gracezhihuizhao was able to put together an Rmd to demonstrate that the unit tests pass and provides a case where a unit test will fail (and what that outcome looks like).

Goal: Add the Rmd file to the package in a location that will allow us to keep together the documentation while also not wrapping it up into the package submitted to CRAN.

From @brown-jason:
check out usethis::use_build_ignore and create a folder called analyses that we can store stuff like this in.  See here: https://stackoverflow.com/questions/13182634/rbuildignore-and-excluding-directories

1. Read the build ignore information
2. Add the unit test demo Rmd
3. Perform any polishing up that may need to be done for future developers to clearly utilize the Rmd for testing.

(Also, please check that the code in "testthat.R"  can be used to test the unit tests.  Looks like one should be able to run that code when the package is installed and obtain the unit test results.  However, when I tried it the code did not work.  Need is just a verification that it works.)

**Comment by gracezhihuizhao** [comment]
@sedavid01 For your question regarding `testthat.R`, please refer to [this link](https://github.com/r-lib/testthat/issues/257). Code in there are not meant to be ran directly.

**Comment by sedavid01** [comment]
Pull request approved, minor updates made, and merge to dev complete.  Closing this ticket.
