### ISSUE TITLE
Update README on CRAN

### ISSUE THREAD

**Issue by kpaulfriedman** [USEPA/CompTox-ToxCast-tcplFit2#6]
Please update the README on CRAN for tcplfit2; it is specific to internal usage and not so helpful for external users. It also provides links to deprecated NCCT bitbucket and user details. It could use an update when the standalone vignette is added.

**Comment by sedavid01** [comment]
Going to assign to @gracezhihuizhao to start on.
Goal: Rename (archive) the current README file, and update current README with background information on package, requirements, and installation.

1. Rename current README to old_README
2. Create a new README file and include the following information:

- System requirements (R and R package requirements)
- Installation instructions - both from git and from CRAN (as well as brief description with regard to differences)
- Contributor list

Start with this for right now please.

@kpaulfriedman please let me know if there is additional information you would like to add to the current list or information in the current README you would like to retain.

@brown-jason and @sedavid01 can help to polish up the README (or provide additional guidance) when the basic information is included.

**Comment by gracezhihuizhao** [comment]
New README is pushed. @sedavid01 and @brown-jason please let me know your thoughts on the information and the format if you have a chance to review it. Thanks!

**Comment by sedavid01** [comment]
@brown-jason and @kpaulfriedman, this ticket has been completed and branch merged into 'dev'.
