### ISSUE TITLE
Update in the tcplfit2 vignette mc4_mthds_id table

### ISSUE THREAD

**Issue by sedavid01** [USEPA/CompTox-ToxCast-tcplFit2#80]
Issue: There is a incorrect/mis-aligned definition regarding the `bmad.aeid.lowconc.nwells` compared with the definition in the mc4_mthds table for tcpl.

Needs:
- [ ] Verify the definition for `bmad.aeid.lowconc.nwells` in tcpl mc4_mthds, and that there are no methods named `bmad.aeid.nwells`.
- [ ] Ensure with the context of the vignette that the table needs updated.
- [ ] Fix the description in the tcplfit2 vignette table describing mc4 bmad methods.

**Comment by madison-feshuk** [comment]
These method desc were updated in tcpl. Need to ensure proper version of tcpl (i.e. definitions on CRAN/v3.1 will differ from what's available on dev branch)
