### ISSUE TITLE
errfun should default to dt4 if not provided to tcplhit2_core

### ISSUE THREAD

**Issue by brown-jason** [USEPA/CompTox-ToxCast-tcplFit2#83]
Based on analysis here: https://github.com/USEPA/CompTox-ToxCast-tcpl/pull/209

https://github.com/USEPA/CompTox-ToxCast-tcplFit2/blob/0b849cf6b7a2425b13c38cc20791d5a6f8d5cebc/R/tcplhit2_core.R#L81

When a parameter is required (in this case errfun) we should check for it and throw a specific error that describes the parameter that is missing.

**Comment by sedavid01** [comment]
This ticket was resolved in tcpl and is no longer necessary for development.  Closing out this ticket.
