### ISSUE TITLE
Vignette Update for Version Release v 0.1.7 of tcplfit2 

### ISSUE THREAD

**Issue by sedavid01** [USEPA/CompTox-ToxCast-tcplFit2#86]
Catch all ticket for vignette updates in the next release of tcplfit2 R package.  More may be added later.

- [x] Update figures with new plotting functionalities.
- [x] Update to mention biphasic modeling 
- [x] Update to mention BMD censoring
- [x] Update to mention distributional choices for error model.
- [ ] Example 1 (and/or 2): Should be able to demonstrate how to use the concRespCore function with a single concentration-response series. May be worth adding some additional details.
- [ ] Either add an example or update Example 1 and/or 2 such that users know how to utilize the tpclfit2_core and tcplhit2_core functions independently, but in sequence.
- [x] Example 4: Update/streamline the example for the 'tcpl' like concentration response modeling.
- [x] Create necessary links between the tcplfit2 and tcpl vignettes.

**Comment by sedavid01** [comment]
@gracezhihuizhao, the Example 1 and 2 "to do's" save for last.  Accomplish the others then we can refine those updates.

**Comment by brown-jason** [comment]
completed
